buildscript {
    ext.kotlin_version = '2.0.0'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

// --- Aluth Namespace Fix eka (afterEvaluate prashne meken nathi wenawa) ---
subprojects {
    project.plugins.withId("com.android.library") {
        def androidExtension = project.extensions.findByName("android")
        if (androidExtension != null) {
            if (androidExtension.namespace == null) {
                androidExtension.namespace = project.group
            }
        }
    }
}